# Generated by Django 4.0.3 on 2022-04-09 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_homebrew_spells_alter_character_character_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('character_class', models.CharField(choices=[('Ranger', 'ranger'), ('Rogue', 'rogue'), ('Wizard', 'wizard'), ('Fighter', 'fighter'), ('Sorcerer', 'sorcerer'), ('Druid', 'druid'), ('Barbarian', 'barbarian'), ('Paladin', 'paladin'), ('Warlock', 'warlock'), ('Monk', 'monk'), ('Bard', 'bard'), ('Cleric', 'cleric')], max_length=50)),
                ('desc', models.CharField(max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='Homebrew_Spells',
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('Ranger', 'ranger'), ('Rogue', 'rogue'), ('Wizard', 'wizard'), ('Fighter', 'fighter'), ('Sorcerer', 'sorcerer'), ('Druid', 'druid'), ('Barbarian', 'barbarian'), ('Paladin', 'paladin'), ('Warlock', 'warlock'), ('Monk', 'monk'), ('Bard', 'bard'), ('Cleric', 'cleric')], max_length=50),
        ),
    ]
