# Generated by Django 4.0.3 on 2022-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_spell_delete_spells_alter_character_character_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(to='main_app.spell'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_class',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='character_class',
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ManyToManyField(to='main_app.character_class'),
        ),
        migrations.AddField(
            model_name='spell',
            name='character_class',
            field=models.ManyToManyField(to='main_app.character_class'),
        ),
    ]
