# Generated by Django 4.0.3 on 2022-04-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_character_class_character_spells_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, to='main_app.spell'),
        ),
    ]
