# Generated by Django 4.0.3 on 2022-04-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
